//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabClick.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLINICA()
        {
            this.EXAME = new HashSet<EXAME>();
            this.LOGIN = new HashSet<LOGIN>();
            this.PACIENTE = new HashSet<PACIENTE>();
            this.TESTE = new HashSet<TESTE>();
        }
    
        public int id { get; set; }
        public int id_laboratorio { get; set; }
        public string nome_clinica { get; set; }
        public string CNPJ { get; set; }
        public string endereco { get; set; }
        public string cep { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string email { get; set; }
        public string logotipo { get; set; }
        public Nullable<System.DateTime> data_inserido { get; set; }
        public Nullable<System.DateTime> data_modificado { get; set; }
    
        public virtual LABORATORIO LABORATORIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAME> EXAME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIN> LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE> PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTE> TESTE { get; set; }
    }
}
