//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabClick.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAME()
        {
            this.RESULTADO = new HashSet<RESULTADO>();
            this.TESTE = new HashSet<TESTE>();
        }
    
        public int id { get; set; }
        public string nome_exame { get; set; }
        public int id_clinica { get; set; }
        public string descricao { get; set; }
        public System.DateTime data_inserido { get; set; }
        public System.DateTime data_modificado { get; set; }
    
        public virtual CLINICA CLINICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADO> RESULTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTE> TESTE { get; set; }
    }
}
