//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabClick.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sql_LabClickEntities : DbContext
    {
        public sql_LabClickEntities()
            : base("name=sql_LabClickEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLINICA> CLINICA { get; set; }
        public virtual DbSet<EXAME> EXAME { get; set; }
        public virtual DbSet<LABORATORIO> LABORATORIO { get; set; }
        public virtual DbSet<LOGIN> LOGIN { get; set; }
        public virtual DbSet<PACIENTE> PACIENTE { get; set; }
        public virtual DbSet<RESULTADO> RESULTADO { get; set; }
        public virtual DbSet<TESTE> TESTE { get; set; }
    }
}
