//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabClick.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
        public Nullable<int> id_clinica { get; set; }
        public Nullable<int> id_laboratorio { get; set; }
        public string perfil { get; set; }
        public Nullable<System.DateTime> data_inserido { get; set; }
        public Nullable<System.DateTime> data_modificado { get; set; }
    
        public virtual CLINICA CLINICA { get; set; }
        public virtual LABORATORIO LABORATORIO { get; set; }
    }
}
