//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabClick.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.TESTE = new HashSet<TESTE>();
            this.TESTE1 = new HashSet<TESTE>();
        }
    
        public int id { get; set; }
        public int id_clinica { get; set; }
        public string nome_paciente { get; set; }
        public string sexo { get; set; }
        public System.DateTime data_nascimento { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string cpf { get; set; }
        public string uf_cidade { get; set; }
        public Nullable<System.DateTime> data_inserido { get; set; }
        public Nullable<System.DateTime> data_modificado { get; set; }
    
        public virtual CLINICA CLINICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTE> TESTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTE> TESTE1 { get; set; }
    }
}
