//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabClick.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADO
    {
        public int id { get; set; }
        public int id_exame { get; set; }
        public int id_teste { get; set; }
        public string laudo { get; set; }
        public string tabela { get; set; }
        public string observacao { get; set; }
        public string documento { get; set; }
        public Nullable<System.DateTime> data_inserido { get; set; }
    
        public virtual EXAME EXAME { get; set; }
        public virtual TESTE TESTE { get; set; }
    }
}
