//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabClick.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TESTE()
        {
            this.RESULTADO = new HashSet<RESULTADO>();
        }
    
        public int id { get; set; }
        public int id_exame { get; set; }
        public int id_clinica { get; set; }
        public int id_paciente { get; set; }
        public string imagem_teste { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_inserido { get; set; }
    
        public virtual CLINICA CLINICA { get; set; }
        public virtual EXAME EXAME { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual PACIENTE PACIENTE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADO> RESULTADO { get; set; }
    }
}
