// <auto-generated />
namespace LabClick.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LabFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LabFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201810022047025_LabFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
